In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [85]:
from MyFunctions import prettify
from nltk import word_tokenize
initialList = ['administrative_professional	maternity_and_family_leave	customer_service_associate	patient_services_coordinator	clinical_admin_team_lead	credentialing_specialist_managed_care	credentialing_specialist_credentialing_verification_office',
'professional_tutor	senior_marketing_executive	united_states_youth_ambassador	sales_trainer_and_blocker	cardiac_stent_researcher	scholarship_ambassador	radiation_oncology_researcher	student_member',
'certified_personal_coach	account_management	healthcare_recruiting_manager	program_director_business_development_travel_nursing	national_recruiting_manager_travelmax	recruiting_supervisor	managing_director',
'realtor	realtor',
'pool_concierge_server	line__prep_cook	account_manager_|_executive_and_technical_recruiter_|_business_consultant	surgeon_recruiter',
'owner	district_sales_manager_for_greater_dayton_area	insurance_sales_representative_pandc_landh	owner	owner_appraiser	owner_appraiser',
'reactive_programming_teaching_assistant	fp101x_teaching_assistant	software_engineer	software_engineer	principal_software_engineer',
'intern	application_engineer	senior_applications_engineer	software_engineer	senior_software_engineer	staff_software_engineer	principal_software_engineer	senior_software_engineering_manager__principal_software_engineer',
'pfs_team_summer_intern	qa_automation_developer_intern	associate_application_developer	software_developer	staff_software_engineer	software_engineer',
'software_engineer	phd_fellow_hp_labs_india	software_engineer	principal_software_engineer	senior_data_science_manager_principal_engineer	senior_data_science_manager_principal_engineer	director_of_machine_learning',
'research_assistant	software_engineer	software_engineer',
'lead_researcher__software_engineer	teaching_assistant	software_development_engineer	senior_software_engineer	staff_software_engineer	software_engineer',
'system_administrator	system_analyst	tech_consultant	senior_principal_consultant	staff_software_engineer',
'software_engineer	software_engineering_intern	senior_software_engineer	senior_software_engineer	engineer',
'programmer_analyst_senior_associate	technical_lead	senior_software_engineer	member_of_technical_staff_1_software_engineer	mts2_software_engineer	manager2_software_development	engineering_manager_architect	senior_engineering_manager',
'it_consultant	software_engineer']
myStrings = []
for each in initialList:
    titles = prettify(each)
    for t in titles:
       myStrings.append(t) 
print(myStrings[0:30])
corpus = myStrings;
vectorizer = CountVectorizer()

['administrative professional', 'maternity and family leave', 'customer service associate', 'patient services coordinator', 'clinical admin team lead', 'credentialing specialist managed care', 'credentialing specialist credentialing verification office', 'professional tutor', 'senior marketing executive', 'united states youth ambassador', 'sales trainer and blocker', 'cardiac stent researcher', 'scholarship ambassador', 'radiation oncology researcher', 'student member', 'certified personal coach', 'account management', 'healthcare recruiting manager', 'program director business development travel nursing', 'national recruiting manager travelmax', 'recruiting supervisor', 'managing director', 'realtor', 'realtor', 'pool concierge server', 'line  prep cook', 'account manager | executive and technical recruiter | business consultant', 'surgeon recruiter', 'owner', 'district sales manager for greater dayton area']


In [86]:
print( vectorizer.fit_transform(corpus) )


  (0, 25)	1
  (1, 3)	1
  (2, 7)	1
  (4, 19)	1
  (4, 38)	1
  (5, 34)	1
  (5, 10)	1
  (6, 34)	1
  (6, 10)	2
  (7, 25)	1
  (8, 17)	1
  (8, 32)	1
  (9, 1)	1
  (10, 30)	1
  (10, 3)	1
  (11, 29)	1
  (12, 1)	1
  (13, 29)	1
  (14, 21)	1
  (16, 0)	1
  (17, 20)	1
  (17, 28)	1
  (18, 13)	1
  (18, 8)	1
  (18, 14)	1
  :	:
  (79, 32)	1
  (79, 7)	1
  (80, 39)	1
  (80, 19)	1
  (81, 15)	1
  (81, 33)	1
  (81, 32)	1
  (82, 22)	1
  (82, 35)	1
  (82, 15)	1
  (82, 33)	1
  (82, 39)	1
  (82, 21)	1
  (83, 15)	1
  (83, 33)	1
  (84, 33)	1
  (84, 13)	1
  (85, 16)	1
  (85, 20)	1
  (86, 16)	1
  (86, 20)	1
  (86, 32)	1
  (87, 9)	1
  (88, 15)	1
  (88, 33)	1


In [94]:
print( vectorizer.vocabulary_ )
print('\n')
print(vectorizer.get_feature_names())
print('\n')
print(vectorizer.stop_words_)

#This is a little block of code that creates a list of words used in the corpus ordered by number.
#It turns out this is useless as the "vectorizer.get_feature_names()" method is the same thing.
keyList = [None] * len(vectorizer.vocabulary_)
for key in vectorizer.vocabulary_:
    keyList[vectorizer.vocabulary_[key]]=key
    
print(keyList)

{'professional': 25, 'and': 3, 'associate': 7, 'team': 38, 'lead': 19, 'credentialing': 10, 'specialist': 34, 'senior': 32, 'executive': 17, 'ambassador': 1, 'sales': 30, 'researcher': 29, 'member': 21, 'account': 0, 'recruiting': 28, 'manager': 20, 'director': 14, 'business': 8, 'development': 13, 'realtor': 26, 'technical': 39, 'recruiter': 27, 'consultant': 9, 'owner': 23, 'appraiser': 5, 'teaching': 37, 'assistant': 6, 'software': 33, 'engineer': 15, 'principal': 24, 'intern': 18, 'application': 4, 'staff': 35, 'engineering': 16, 'developer': 12, 'data': 11, 'science': 31, 'of': 22, 'system': 36, 'analyst': 2}


['account', 'ambassador', 'analyst', 'and', 'application', 'appraiser', 'assistant', 'associate', 'business', 'consultant', 'credentialing', 'data', 'developer', 'development', 'director', 'engineer', 'engineering', 'executive', 'intern', 'lead', 'manager', 'member', 'of', 'owner', 'principal', 'professional', 'realtor', 'recruiter', 'recruiting', 'researcher', 'sales', 'sc

In [84]:
test = vectorizer.transform([' administrative professional maternity and family leave customer service associate patient services coordinator clinical admin team lead credentialing specialist managed care credentialing specialist credentialing verification office',' software developer intern teaching assistant software engineer software engineer software engineer','senior technical recruiter', 'software engineer software engineer software engineer software engineer software engineer software engineer software engineer software engineer software engineer software engineer software engineer software engineer software engineer software engineer', 'computer programmer', 'technical program manager', 'machine leraning specialist and data analyst'])
print(test.toarray())

[[ 0  0  0  0  0  0]
 [ 3  0  0  0  4  0]
 [ 0  0  0  1  0  0]
 [14  0  0  0 14  0]
 [ 0  0  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  0  0  0  0]]


Now that we have the model, we can turn each row in the data set into a vector for the dataframe.

In [6]:
#Each career path becomes it own list. 
pathList = [] # The list of career path lists
DataFile = open("/Users/gregorycolledge/gcolledge/gcolledge/MSD_6019/allPaths.txt");
for i in range(0,1000):
    careerPath = DataFile.readline();
    careerPathList = prettify(careerPath);
    pathString = ""
    for title in careerPathList:
        pathString = pathString + " " + title
    pathList.append([pathString]);
DataFile.close();
print(pathList[:10])

[[' software developer intern teaching assistant software engineer software engineer software engineer'], [' israel sociological society cochairman of gender comunity founder and coeditor of migdar (gender) academic journal lecturer book author'], [' member ceo member of the board president member of the board member of the board'], [' editorial assistant editorial assistant'], [' dr med neuroradiologist dr med radiology departement dr med specialised in neuroradiology and head and neck radiology neuroradiologue fmh et radiologue orl'], [' president chair endovascular and interventional neurology section director interventional neurology codirector neroendovascular surgery professor of neurology and neurosurgery fellow of society of vascular and interventional neurology faha (fellow of american heart association) fellow of american academy of neurology'], [' especialista de neurocirugia especialista de neurocirugia especialista de neurocirugia  especialista de neurocirugia mdico especi

In [17]:
vectorizedRows = []
for path in pathList:
    temp = vectorizer.transform(path)
    vectorizedRows.append(temp.toarray())
print(len(vectorizedRows))
print(vectorizedRows[:10])

1000
[array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0]]), array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0]]), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0

In [45]:
from sklearn.cluster import KMeans
import numpy as np

At this point, the vectorizedRows list is a List of arrays. Each array is a 1 by 119. So there are 119 features in this model...I think.

In [49]:
print(np.array(vectorizedRows).shape)
print(np.array(vectorizedRows).reshape(1000,119).shape)
kmeans = KMeans(n_clusters=3, random_state=4)
kmeans.fit(np.array(vectorizedRows).reshape(1000,119))


(1000, 1, 119)
(1000, 119)


In [68]:
print(np.array(test.toarray()).shape)
result = kmeans.predict(np.array(test.toarray()))
print(result)

(7, 119)
[0 1 0 1 0 0 0]
